kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
spec:
  # one pod can contain multiple containers
  containers:
  - name: nginx # name of our container
    image: nginx # actual image name