kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.doccker.com/"
spec:
  containers:
  - name: nginx
    image: nginx