apiVersion: v1
kind: Secret
metadata:
  name: dotfile-Secret
type: Opaque
data:
  username: OUub77B= # base64 encoded text of admin (command => echo -n "admin" | base64)
  password: DQnj23J= # same as above